apiVersion: harmony.io/v1alpha1
kind: S3Bucket
metadata:
  name: rag-med
  annotations:
    harmony.io/deletion-policy: retain
spec:
  provider: aws
  region: us-east-1
  bucketName: rag-med
  endpoint: "http://localhost:4566"
  accessKeyId: "@Secret/minio-access-key-id"
  secretAccessKey: "@Secret/minio-secret-access-key"
