apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
    - name: gateway
      port: 4566
      targetPort: 4566
      nodePort: 30566
      protocol: TCP
